// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generateValidGrids
List generateValidGrids(int size);
RcppExport SEXP _TakuzuKL_generateValidGrids(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(generateValidGrids(size));
    return rcpp_result_gen;
END_RCPP
}
// generateValidRows
List generateValidRows(int size);
RcppExport SEXP _TakuzuKL_generateValidRows(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(generateValidRows(size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TakuzuKL_generateValidGrids", (DL_FUNC) &_TakuzuKL_generateValidGrids, 1},
    {"_TakuzuKL_generateValidRows", (DL_FUNC) &_TakuzuKL_generateValidRows, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TakuzuKL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
