# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateValidGrids <- function(size) {
    .Call(`_TakuzuKL_generateValidGrids`, size)
}

generateValidRows <- function(size) {
    .Call(`_TakuzuKL_generateValidRows`, size)
}

